<?php

namespace Database\Seeders;

use App\Models\tenant\Matrix;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MatrixSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $matrixs = [
            "Solución Captadora",
            "Solución Captadora",
            "Solución Captadora",
            "Solución Captadora",
            "Solución Captadora",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Filtro",
            "Aire",
            "Filtro",
            "Aire",
            "Filtro",
            "Aire",
            "Filtro",
            "Aire",
            "Filtro",
            "Aire",
            "Filtro",
            "Aire",
            "Tubo de Carbon Activado",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Tubo de Carbon Activado",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Aire",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Filtro",
            "Aire",
            "Filtro",
            "RUIDO AMBIENTAL: PLANTAS INDUSTRIALES",
            "RUIDO AMBIENTAL: TRÁFICO AÉREO",
            "RUIDO AMBIENTAL: TRÁFICO FERROVIARIO",
            "RUIDO AMBIENTAL: TRÁFICO RODADO",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Suelo",
            "Emisiones",
            "Emisiones",
            "Emisiones",
            "Emisiones",
            "Emisiones",
            "Emisiones",
            "Emisiones",
            "Emisiones",
        ];

        foreach ($matrixs as $val) {
            Matrix::firstOrCreate([
                'description' => $val,
            ]);
        }
    }
}
