<?php

namespace Database\Seeders;

use App\Models\tenant\Parameters;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ParameterSeeder extends Seeder
{
    public function run(): void
    {
        $parameters = [
            "- Dióxido de Nitrógeno (NO2).",
            "- Monóxido de Carbono (CO).",
            "- Sulfuro de Hidrógeno (H2S).",
            "- Ozono (O3).",
            "- Dióxido de Azufre (SO2).",
            "- Monóxido de Carbono (CO) ⁽ᵇ⁾",
            "- Sulfuro de Hidrógeno (H2S) ⁽ᶜ⁾",
            "- Ozono (O3) ⁽ᵇ⁾",
            "- Dióxido de Nitrógeno (NO2) ⁽ᵃ⁾",
            "- Dióxido de Azufre (SO2) ⁽ᶜ⁾",
            "- Material particulado  PM2.5 (Alto volumen)",
            "- Determinación de peso en Filtros PM2.5 Alto volumen.",
            "- Material Particulado PM10 (Alto volumen).",
            "- Determinación de peso en Filtros PM10 Alto volumen.",
            "- Material Particulado PM2.5 (Bajo volumen).",
            "- Determinación de Peso en Filtros PM2.5 Bajo volumen.",
            "- Material particulado PM10 (Bajo volumen).",
            "- Determinación de peso en Filtros PM10 Bajo volumen.",
            "- Partículas Respirables ",
            "- Determinación de peso: Partículas Respirables ",
            "- Partículas Totales o Inhalable",
            "- Determinación de peso: Partículas Totales o Inhalables",
            "- Hidrocarburos Totales expresados como Hexano ⁽ᵇ⁾",
            "- Hidrocarburos Totales expresados como Hexano.",
            "- Benceno ⁽ᶜ⁾",
            "- Monóxido de Carbono (Automáticos)",
            "- Dióxido de Nitrógeno (Automáticos)",
            "- Sulfuro de Hidrógeno (Automáticos)",
            "- Dióxido de Azufre (Automáticos)",
            "- Benceno.",
            "METALES:_Aluminio, Arsénico, Bario, Berilio, Boro, Calcio, Cadmio, Cobalto, Cromo, Cerio, Cobre, Hierro, Mercurio, Potasio, Litio, Magnesio, Manganeso, Molibdeno, Níquel, Sodio, Fosforo, Plomo, Antimonio, Selenio, Sílice  (SiO2), Estroncio, Estaño, Titanio, Talio, Vanadio, Zinc",
            "- Aluminio",
            "- Arsénico",
            "- Boro",
            "- Bario",
            "- Berilio",
            "- Calcio",
            "- Cadmio",
            "- Cerio",
            "- Cobalto",
            "- Cromo",
            "- Cobre",
            "- Hierro",
            "- Mercurio",
            "- Potasio",
            "- Litio",
            "- Magnesio",
            "- Manganeso",
            "- Molibdeno",
            "- Sodio",
            "- Niquel",
            "- Fósforo",
            "- Plomo",
            "- Antimonio",
            "- Selenio",
            "- Sílice",
            "- Estaño",
            "- Estroncio",
            "- Titanio",
            "- Talio",
            "-Vanadio",
            "- Zinc",
            "- Aluminio.*",
            "- Arsénico.*",
            "- Boro.*",
            "- Bario.*",
            "- Berilio.*",
            "- Calcio.*",
            "- Cadmio.*",
            "- Cerio.*",
            "- Cobalto.*",
            "- Cromo.*",
            "- Cobre.*",
            "- Hierro.*",
            "- Mercurio.*",
            "- Potasio.*",
            "- Litio.*",
            "- Magnesio.*",
            "- Manganeso.*",
            "- Molibdeno.*",
            "- Sodio.*",
            "- Niquel.*",
            "- Fósforo.*",
            "- Plomo.*",
            "- Antimonio.*",
            "- Selenio.*",
            "- Silicio.*",
            "- Estaño.*",
            "- Estroncio.*",
            "- Titanio.*",
            "- Talio.*",
            "- Vanadio.*",
            "- Zinc.*",
            "- Hidrocarburos No Metano (HCNM) *",
            "- Hidrocarburos No Metano (HCNM) *",
        ];

        foreach ($parameters as $val) {
            Parameters::firstOrCreate([
                'description' => $val,
            ]);
        }
    }
}
