<?php

namespace Database\Seeders;

use App\Models\tenant\Parameters;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ParameterSeeder extends Seeder
{
    public function run(): void
    {
        $parameters = [
            'Aceites y Grasas',
            'Aceites y Grasas (suelo)',
            '%O2',
            'Aceleración',
            'Acidez',
            'Ácido cianhidrico',
            'Ácido clorídrico',
            'Acido fluorhidrico',
            'Ácido nítrico ',
            'Acido perclorico',
            'Acido perclorhidrico',
            'Acido Sulfhídrico',
            'Ácido Sulfúrico ',
            'Alcalinidad por Bicarbonatos',
            'Alcalinidad por Carbonatos',
            'Alcalinidad Total',
            'Aluminio',
            'Aniones ',
            'Amoníaco ',
            'Amonio ',
            'Análisis Granolumétrico por tamizado',
            'AP 42 (CALCULO-MATERIAL PARTICULADO)',
            'Arsénico - Metales (ICP-AES)',
            'Arsénico  (PM10 alto volumen)',
            'Arsénico  (PM10 bajo volumen)',
            'Arsénico  (PM2.5 alto volumen)',
            'Arsénico  (PM2.5 bajo volumen)',
            'Benceno  ',
            'Benzoapireno',
            'Btex (suelo)',
            'Btex (agua)',
            'Bicarbonatos',
            'Bifenilos policlorados (PCBs) ',
            'Bromuro',
            'Cadmio (PM 10 bajo volumen)',
            'Cadmio (PM 10 alto volumen)',
            'Calcio',
            'Campo Eléctrico',
            'Campo Magnético',
            'Capacidad de Intercambio Catiónico',
            'Carbonato de calcio (CaCO3)',
            'Carbonatos',
            'Caudal ',
            'Caudal ultrasonico ',
            'Cianuro Libre',
            'Cianuro Total',
            'Cianuro WAD',
            'Cloro Residual (Libre)  ',
            'Cloro Total ',
            'Cloruro',
            'Cloruro de mercurio ',
            'CO (CTM 34)',
            'CO2 (Parametro NO ACREDITADO)',
            'Cobalto',
            'Cobre',
            'Compuestos Orgánicos Volatiles (aire)',
            'Compuestos Orgánicos Volatiles (agua)',
            'Compuestos Orgánicos Volatiles (suelo)',
            'Color',
            'Conductividad- suelo',
            'Conductividad Electrica (suelo)',
            'Confort Termico',
            'Contenido de Humedad (suelo)',
            'Cromo (PM10  bajo volumen)',
            'Cromo (PM10  alto volumen)',
            'Cromo Hexavalente',
            'Cromo Hexavalente - Suelo',
            'Demanda  Química de Oxígeno',
            'Demanda Bioquímica de Oxigeno',
            'Densidad de flujo magnetico',
            'Densidad de Potencia',
            'Desplazamiento',
            'Determinación de flujo ',
            'Det. Peso Filtros PM 2.5 HV',
            'Det. Peso Filtros PM 2.5 LV',
            'Det. Peso Filtros PM10 HV',
            'Det. Peso Filtros PM10 LV',
            'Det. Peso Filtros PTS ',
            'Det. Peso Partículas Respirables.',
            'Det. Peso Partículas Totales o Inhalable.',
            'Detergentes (SAAM)',
            'Dióxido de Azufre',
            'Dióxido de azufre (SO2)',
            'Dióxido de azufre (SO2) AUTOMATICO',
            'Dióxido de azufre (SO2) -CTM 34',
            'Dióxido de Azufre EPA 6C',
            'Dióxido de Azufre EPA 6',
            'Dióxido de carbono',
            'Dióxido de carbono (CO2)',
            'Dióxido de Nitrógeno (NO2)',
            'Dióxido de Nitrógeno (NO2) AUTOMATICO',
            'Dióxido de Nitrógeno (NO2)-CTM 34',
            'Dióxido de Nitrógeno (NO2)-CTM 22',
            'Dosimetrìa',
            'Dureza Cálcica',
            'Dureza Magnesica',
            'Dureza Total',
            'Emisiones Testo',
            'Enjuague epa 29',
            'Envase N°4 (HNO3 + H2O2)',
            'Enjuague 5 y 6 (HCI) epa 29',
            'Enjuague IMP. 4 (HNO3) (EPA 29)',
            'EPA 6C',
            'EPA 7E',
            'EPA 10',
            'Esteres Ftalatos',
            'Estrés térmico',
            'Estrés térmico por calor',
            'Estrés térmico por frio',
            'Electric field intensity',
            'Fauna (No acreditado)',
            'Fenoles',
            'Flora (No acreditado)',
            'Flow',
            'FLOW ISO 12242:2012',
            'Flujo Magnetico ',
            'Fluoruro',
            'Formas Parasitarias',
            'Fosfato ',
            'Fosforo soluble',
            'Fosforo Total',
            'Fuerza de campo magnetico ',
            'Fracción 1 (C6-C10)',
            'Fración 2 (C10-C28)',
            'Fracción 3 (C28-C40)',
            'H2 AP 42 ',
            'H2S AP 42 ',
            'Hexano',
            'Hidrocarburos Aromaticos Polinucleares (PAHs)',
            'Hidrocarburo No Metano HCNM (No acreditado)',
            'Hidrocarburo No Metano (AP 42)',
            'Hidrocarburo total de petroleo (HTP C10-C40)',
            'Hidrocarburos Totales Expresado como Hexano(HTC)',
            'Hidrocarburos Totales (CTM022)',
            'Hierro',
            'Hierro  (PM10 alto volumen)',
            'Hierro  (PM10 bajo volumen)',
            'Hierro  (PM2.5 bajo volumen)',
            'Hierro (Disuelto)',
            'Humedad',
            'Hidrocargburo de Petroleo ORGANOLEPTICO',
            'Hidrocarburos Totales de Petróleo (C28-C40)',
            'Hidrocarburos No Metano (HNM)',
            'HUMOS METALICOS ',
            'Humos metálicos (Hg, As)',
            'Humos metálicos (Pb, Zn, Cd)',
            'Humos metálicos (Pb, Zn, Cd,As,Sb,Co)',
            'Humos no metánicos',
            'Humidity ( method 04)',
            'Iluminacion',
            'Intensidad de campo electrico',
            'Intensidad de campo magnetico',
            'Intensidad de flujo magnetico',
            'Intensidad de Potencia (W/m2)',
            'Ion Amonio',
            'Macrobentos',
            'Magnesio',
            'Manganeso',
            'Material Flotante',
            'Materia Orgánica, Carbono Orgánico Total(COT)',
            'Material Particulado AP 42',
            'Material Particulado EPA 5',
            'Material Particulado EPA 29',
            'Material Partículado PM10 HV',
            'Material Partículado PM10 LV',
            'Material Particulado PM2.5 HV',
            'Material Partículado PM2.5 LV',
            'Material Particulado PTS',
            'Magnetic Field Strength',
            'Magnetic Flux Density',
            'Mediciones de campo',
            'Mercurio (PM 10 Alto Volumen)',
            'Metal(Aluminio)',
            'Metales Disuelto (Uranio)',
            'Metales Disueltos',
            'Metales disueltos por ICP',
            'Metales Totales (Litio)',
            'Metales Totales (Uranio)',
            'Metales (EPA 29) Hg',
            'Metales (EPA 29) As, Pb y Hg',
            'Metales (EPA 29) ',
            'Lavado de Sonda (EPA-29)',
            'Metales en PM10 (Pb, As, Cd,Cr)',
            'Metales PM10 HV',
            'Metales PM10 LV',
            'Metales PM2.5 HV',
            'Metales PM2.5 LV',
            'Metales (ICP AES)',
            'Metales Totales (ICP OES)',
            'Metales Totales (ICP-OES) (uranio)',
            'Metales Totales (ICP-AES) (cobre)',
            'Metales Totales (Hierro)',
            'Metales Totales (Plomo)',
            'Metano (CH4) AP 42',
            'Meteorologia',
            'Meteorologia radiación solar',
            'Mercurio gaseoso (hg)',
            'Mercurio gaseoso (hg) AUTOMATICO',
            'Monóxido de carbono (CO)',
            'Monóxido de carbono (CO) AUTOMATICO',
            'Monóxido de carbono (CO) -CTM34',
            'Monóxido de carbono (CO) -CTM30',
            'Monoxido de Carbono (EPA-10)',
            'Monoxido de Carbono (EPA-3A)',
            'MPT',
            'N2 AP 42 ',
            'Neblina ácida (ácido nítrico)',
            'Neblina ácida (ácido sulfúrico)',
            'NH3 (A partir del NO2)',
            'Nitratos ',
            'Nitratos + Nitritos ',
            'Nitritos ',
            'Nitrógeno Amoniacal',
            'Nitrógeno Total',
            'Nitrógeno-Nitratos',
            'Nitrógeno-Nitritos',
            'Nivel freatico ',
            'NO (CTM 22)',
            'Nox (Method 7E)',
            'NOx ',
            'NOx (AUTOMATICO)',
            'Nox (CTM-030)',
            'NOx (CTM034)',
            'Olor',
            'Óxido Nítrico',
            'Oxidos de nitrógeno (NOX) CTM 34',
            'Oxidos de nitrógeno (NOX) CTM 22',
            'Oxidos de nitrogeno (EPA 7)',
            'Óxidos Nitrosos (AUTOMATICO)',
            'Oxígeno (O2) CTM 34',
            'Ozono (O3)',
            'Ozono (O3) AUTOMATICOS',
            'O2-CTM034',
            'O2- METHOD 3A',
            'Particula Flotante',
            'PARTICULAS (AP42)',
            'Partículas Respirables.',
            'Particulas Respirables/Humos metálicos (Pb, Cd, Zn)',
            'Partículas Totales o Inhalable.',
            'Pesticidas Organoclorados',
            'Pesticidas Organoclorados (suelo)',
            'Pesticidas Organofosforados',
            'Power Density',
            'pH suelo',
            'Plomo (Metales AP42 )',
            'Plomo (PM10 alto volumen)',
            'Plomo (PM10 bajo volumen)',
            'Plomo (PM2.5 alto volumen)',
            'Plomo (PM2.5 bajo volumen)',
            'Potasio',
            'Potencial Redox ',
            'PTS (PM 10 HV)',
            'Presion (Method 2)',
            'Radiacion Electromagnetica',
            'Radiacion NO Ionizante',
            'Radiacion UV',
            'Radiación UV',
            'RAE CO2',
            'Recuperaco Epa 29',
            'Recuperado IM. 5 y 6 (KMnO4 ACIDO) (EPA29)',
            'Recuperaco Epa 5',
            'Riesgos disergonomicos',
            'Riesgos Psicosociales',
            'Ruido Ambiental',
            'Ruido Ambiental Diurno',
            'Ruido Ambiental Nocturno',
            'Ruido Continuo (24h)',
            'Ruido Continuo (08h)',
            'Ruido Ocupacional',
            'Sabor',
            'Salinidad',
            'Silice cristalina respirables',
            'SO2 (EPA 6C)',
            'Sodio',
            'Sólidos Sedimentables',
            'Sólidos Suspendidos Totales',
            'Sólidos Totales',
            'Sólidos Totales Disueltos',
            'Solidos Volátiles',
            'Solucion de Lavado EPA 5',
            'Solucion de recuperado H2O2 (EPA 16 A)',
            'Solucion de recuperado Buffer de Citrato(EPA 16 A)',
            'SOLUCION EPA-16A',
            'Solucion de Lavado (HNO3 METHOD 29)',
            'SONOMETRIA',
            'Sulfato',
            'Sulfito',
            'Sulfuro ',
            'Sulfuro de hidrógeno (H2S)',
            'Sulfuro de hidrógeno (EPA 16)',
            'Sulfuro de hidrógeno (Epa 18)',
            'Sulfuro de hidrógeno (H2S) AUTOMATICO',
            'Sulfuro de hidrógeno (H2S CTM34)',
            'Textura',
            'Trihalometanos ',
            'Tolueno',
            'TRS (Epa 16A)',
            'Temperatura (Method 2) ',
            'Velocidad',
            'Vibracion',
            'Vibración ambiental',
            'Vibración en edificios',
            'Vibracion Cuerpo Completo',
            'Vibración cuerpo completo ',
            'Vibraciòn Ocupacional Cuerpo Entero',
            'VOC´S',
            'Volatile Organic Compounds (EPA Method 18)',
            'Xileno',
            'Zinc (Metales Totales ICP-OES)',
            'Zinc  (PM10 alto volumen)',
            'Zinc  (PM10 bajo volumen)',
            'Zinc  (PM2.5 alto volumen)',
            'Zinc  (PM2.5 bajo volumen)',
            'T° en Campo',
            'Conductividad en Campo',
            'Caudal (campo)',
            'Cloro Residual (Libre)  ',
            'Cloro Totall (Campo)  ',
            'Oxígeno Disuelto en Campo',
            'pH en Campo',
            'Potencial Redox ',
            'Resistividad en campo',
            'Turbidez en campo',
            'Salinidad (campo)',
            'Flow',
            'Water level',
            '% Materia Orgánica **',
            'Aldicarb **',
            'Aniones **',
            'Bacterias Heterotroficas**',
            'Bicarbonatos',
            'Bifenilos policlorados (PCBs) (**)',
            'BTEX **',
            'Cadmio(PM10 alto volumen)',
            'Cianotoxinas**',
            'Clorofila A**',
            'Cloruro (CL-)',
            'Coliformes Fecales o termotolerantes**',
            'Coliformes Totales**',
            'Color**',
            'Cromo (PM10 alto volumen}',
            'E. Coli**',
            'Enteroccocos**',
            'Escherichie coli**',
            'Etilbenceno',
            'Fitoplacton**',
            'Fitoplancton cuantitativo**',
            'Fitoplancton cualitativo**',
            'FLOW ISO 12242:2012',
            'Formas Parasitarias **',
            'Fosfato  (PO4)-3',
            'Fósforo',
            'H. Bacterias (**)',
            'Helmintn Eggs**',
            'HTP**',
            'Hongos**',
            'Humos metálicos **',
            'Larvas**',
            'Macrobentos**',
            'Macroinvertebrados**',
            'Macrozobentos / Macroinvertebrados *',
            'Material flotante cleosen f Anthropogenic',
            'Metales ICP **',
            'Nemátodos',
            '"Nitratos (NO3--N) +',
            'Nitritos (NO2--N)"',
            'Nitrogeno Total*',
            'Olor ',
            'O.V.L.**',
            'Oil & Grease**',
            'Parasitos y protozoarios **',
            'Particulas Flotantes *',
            'Pesticidas Carbamatos (Aldicarb) (**)',
            'Pesticidas organoclorados (**)',
            'Pesticidas organofosforados (Parathion) (**)',
            'Phytoplankton Quantitative *',
            'Polychlorinated Biphenyls (PCB´s) **',
            'Polynuclear Aromatic Hydrocarbons - PAHs **',
            'Protozoarios Patógenos**',
            'PTS',
            'quistes ooquistes**',
            'Radiacion UV **',
            'Salmonella spp **',
            'Surfactantes Anionicos',
            'Thermotolerantes Fecales (**)',
            'TPH (C10-C28)**',
            'TPH (C11-22)**',
            'TPH (C10-C40)**',
            'Trihalometanos **',
            'Vibrio Cholerae**',
            'Virus **',
            'Xileno**',
            'Zooplacton**',
            'Zooplankton Quantitative *',
            'Zooplancton cuantitativo*',
            'Zooplancton cualitativo*',
            'NOx (CTM-022)',
            'NOx (CTM-034)',
            'Nox (No y No2) EPA 7',
            'NO (CTM-022)',
            'NO (CTM-34)',
            'NO2 (CTM-022)',
            'NO2 (CTM-34)',
            'CO (EPA 10)',
            'CO (CTM34)',
            'Bario - Metales Totales (ICP-AES)',
            'Mercurio gaseoso total',
            'Metales (ICP-AES)',
            'Benzene',
            'Solucion EPA -16A',
            'Metales en filtro',
            'Variación de T° C ',
            'Metales Totales (ICP OES) (CADMIO)',
            'Turbidez',
            'Oxigeno Disuelto',
            'Litio - Metales (ICP-AES) ',
            'Cadmio - Metales (ICP-AES)',
            'Mercurio - Mateales (ICP-AES)',
            'Plomo - Metales (ICP-AES)',
            'Arsenico - Metales (ICP-AES)',
            'Cromo - Metales (ICP-AES)',
            'Cianuro libre (Suelo)',
            'Metales (ICP-AES) Arsenico, Bario, Cadmio, Plomo, Mercurio - Suelo'
        ];

        Parameters::create([
            'type' => 'reception',
            'content' => $parameters,
        ]);
    }
}
