<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ReferenceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $references = [
            ["code" => "ASTM D1607-91 (validado modificado). No incluye muestreo. (2018)", "title" => "Método de prueba estándar para el contenido de dióxido de nitrógeno de la atmósfera (reacción de Griess-Saltzman).",],
            ["code" => "GREENLAB - 009. (Basado en EPA Method 10A) (validado). No incluye muestreo. (2018)", "title" => "Determinación de Monóxido de Carbono en la atmósfera.",],
            ["code" => "Method of Air Sampling and Analysis. James P. Lodge, Jr., 3rd Ed: 1989. Part 701 - (Validado Modificado). No incluye muestreo. (2018)", "title" => "Determinación de la concentración de sulfuro de hidrógeno (H2S) en la atmósfera",],
            ["code" => "GREENLAB-010 (Basado en Lodge James, Methods of air sampling and analysis, 401) (validado). No incluye muestreo. (2018)", "title" => "Método de Determinación de Ozono en la Atmósfera.",],
            ["code" => "EPA CFR 40. Appendix A-2 to part 50. (validado modificado). No incluye muestreo. (2018)", "title" => "Método de referencia para la determinación de dióxido de azufre en la atmósfera. (Método Pararosanilina).",],
            ["code" => "GREENLAB-006 (Basado en EPA Method 10A) (validado) (2018)", "title" => "Determinación de Monóxido de Carbono en la atmósfera.",],
            ["code" => "James P. Lodge Jr. - Methods of Air Sampling and Analysis, Third Edition, Part 701. 1980 (Validado-Modificado). (2018)", "title" => "Determinación de la concentración de sulfuro de hidrógeno (H2S) en la atmósfera",],
            ["code" => "GREENLAB-001. (Basado en EPA CFR 40. Appendix J to part 50)(validado). (2018)", "title" => "Método de Determinación de Ozono en la Atmosfera.",],
            ["code" => "ASTM D1607-91 (2018)", "title" => "Standard Test Method for Nitrogen Dioxide Content of the Atmosphere (Griess-Saltzman Reaction)",],
            ["code" => "EPA CFR 40. Appendix A-2 to part 50. (2018)", "title" => "Reference Method for the Determination of Sulfur Dioxide in the Atmosphere (Pararosaniline Method)",],
            ["code" => "EPA CFR 40. Appendix J to part 50 (Validado aplicado fuera del alcance). (2018)", "title" => "Reference method for the determination of particulate matter as PM10 in the atmosphere.",],
            ["code" => "GREENLAB-003. (Basado en EPA CFR 40, Appendix J to part 50) (validado aplicado fuera del alcance).No incluye muestreo. (2018)", "title" => "Reference method for the determination of particulate matter as PM10 in the atmosphere",],
            ["code" => "NTP 900.030 (2018)", "title" => "GESTIÓN AMBIENTAL. Calidad de aire. Método de referencia para la determinación de material particulado respirable como PM10 en la atmósfera.",],
            ["code" => "GREENLAB-002  (Basado en EPA CFR 40. Appendix J to part 50). (Validado). No incluye muestreo. (2018)", "title" => "Reference method for the determination of particulate matter as PM10 in the atmosphere.",],
            ["code" => "EPA CFR 40, Part 50,Appendix L. (2018)", "title" => "Method for the Determination of Fine Particulate Matter as PM2.5 in the Atmosphere.",],
            ["code" => "GREENLAB-005. (Basado en EPA CFR 40, Part 50, Appendix L).(validado modificado). No incluye muestreo. (2018)", "title" => "Reference method for the determination of fine particulate matter as PM2.5 in the atmosphere.",],
            ["code" => "EPA-Compendium, Method IO-2.3 (1999)", "title" => "Sampling of Ambient air for PM 10 concentration using The Rupprecht and Patashnick (R&P) Low Volume Partisol Sampler.",],
            ["code" => "GREENLAB-004. (Basado en EPA Compendium Method IO-2.3) (validado modificado). No incluye muestreo. (2018)", "title" => "Sampling of Ambient Air for PM10 Concentration Using the Rupprecht and Patashnick (R&P). Low Volumen Partisol Sampler.",],
            ["code" => "NIOSH 0600. Isuue 3 (1998)", "title" => "Particulates not otherwise regulated, Respirable.",],
            ["code" => "NIOSH 0600.Issue 3 (validado modificado).No incluye muestreo. (2018)", "title" => "Particulates not otherwise regulated. Respirable.",],
            ["code" => "NIOSH 0500. Isuue 2. (1994)", "title" => "Particulates not otherwise regulated,  Total.",],
            ["code" => "NIOSH 0500, Issue 3 (validado modificado). No incluye muestreo. (2018)", "title" => "Particulates not otherwise regulated. Total.",],
            ["code" => "ASTM D3687 - 19 (2019)", "title" => "Standard Test Method for Analysis of Organic Compound Vapors Collected by the Activated Charcoal Tube Adsorption Method",],
            ["code" => "ASTM D3687 - 19 (2019) (VALIDADO-modificado). (2020)", "title" => "Standard Practice for Analysis of Organic Compound Vapors Collected by the Activated Charcoal Tube Adsorption Method",],
            ["code" => "UNE-EN 14662-2  (2006)", "title" => "Calidad del aire ambiente. Método normalizado de medida de las concentraciones de benceno. Parte 2: Muestreo por aspiración seguido de desorción por disolvente y cromatografía de gases",],
            ["code" => "NTP-ISO 4224: 2019 (revisada el 2025) ", "title" => "Aire ambiental. Determinación de monóxido de carbono. Método de espectrometría infrarroja no dispersiva ",],
            ["code" => "NTP-ISO 7996: 2019 (revisada el 2025) ", "title" => "Aire ambiental. Determinación de la concentración másica de óxidos de nitrógeno. Método de quimioluminiscencia ",],
            ["code" => "NTP-ISO 10498: 2017  (VALIDADO-modificado) (2020)", "title" => "Determinación de sulfuro de hidrogeno por el  Método de Fluorescencia ultravioleta ",],
            ["code" => "NTP-ISO 10498 2017/COR 1:2017 (2017)", "title" => "Aire ambiental. Determinación de dióxido de azufre. Método de Fluorescencia ultravioleta CORRIGENDA 1 1ª Edición ",],
            ["code" => "ASTM D3687 - 19 (VALIDADO-modificado). (2020)", "title" => "Standard Test Method for Analysis of Organic Compound Vapors Collected by the Activated Charcoal Tube Adsorption Method",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. //Determination of metals in ambient particulate matter using inductively coupled plasma (ICP) spectroscopy. ",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "EPA Compendium METHOD IO-3.1 // EPA Compedium METHOD IO-3.4 (1999)", "title" => "Selection, preparation and extraction of filter material. // Determination of metals in ambient particulate matter using inductively coupled plasma (icp) spectroscopy.",],
            ["code" => "ASTM D3687 - 07 (Reapproved 2012) (2007)", "title" => "Standard Practice for Analysis of Organic Compound Vapors Collected by the Activated Charcoal Tube Adsorption Method",],
            ["code" => "ASTM D3687 - 07  2012 (VALIDADO-modificado). No Incluye muestreo. (2022)", "title" => "Standard Practice for Analysis of Organic Compound Vapors Collected by the Activated Charcoal Tube Adsorption Method",],

        ];

        foreach ($references as $value) {
            ReferencesStandard::firstOrCreate([
                'code' => $value['code'],
                'title' => $value['title']
            ]);
        }
    }
}
